### ISSUE TITLE
type error in LeadSubscriber

### ISSUE THREAD

**Issue by pety-dc** [TheDMSGroup/mautic-enhancer#74]
Mautic version: 2.14.1
Mautic-enhancer version: 2.14.2

I accedentally run mautic (2.14.1) with enhancer version 2.14.2. due to composer version set to "~2".
This cross-version usage causes a type error:

```
mautic.ERROR: PHP Error - Object of class DateTime could not be converted to string - in file /var/www/html/plugins/MauticEnhancerBundle/EventListen
er/LeadSubscriber.php - at line 71 [] []
```

I wonder if the same happens with mautic 2.14.2. 
Anyway, I reverted enhancer version to 2.14.0. I just thought I should leave a note about the issue.

**Comment by heathdutton** [comment]
Could you try upgrading to the latest master branch to see if the issue continues?

**Comment by pety-dc** [comment]
Hey @heathdutton 
I upgraded to mautic 2.14.2 and mautic enhancer 2.14.2 and experiance the same issue.

I believe the problem is that in the LeadSubscriber eventlistener in the doAutoRunEnhancements method 
`$lead->getLastActive()` returns a DateTime object and implode can't convert it to string

`implode(
                    '|',
                    [
                        $lead->getFirstname(),
                        $lead->getLastActive(),
                        $lead->getEmail(),
                        $lead->getPhone(),
                        $lead->getMobile(),
                    ]
                )`

I wonder how you do not run into this error?

**Comment by pety-dc** [comment]
Moreover, `$lead->getLastActive` can be null

$leadKey generation should look like:

> `$leadKey = strtolower(
>                 implode(
>                     '|',
>                     [
>                         $lead->getFirstname(),
>                         $lead->getLastActive()?$lead->getLastActive()->format('Y-m-d H:i:s'):'',
>                         $lead->getEmail(),
>                         $lead->getPhone(),
>                         $lead->getMobile(),
>                     ]
>                 )
>             );
> `

Or use serialize instead of implode which can handle objects

> `$leadKey = md5(
>                 serialize(
>                     [
>                         $lead->getFirstname(),
>                         $lead->getLastActive(),
>                         $lead->getEmail(),
>                         $lead->getPhone(),
>                         $lead->getMobile(),
>                     ]
>                 )
>             );
> `

**Comment by heathdutton** [comment]
I think in our case 99.9% of our 100mil+ leads do not have a lastActive entry at all since  they are externally sourced, that's why we didn't see this issue. Thanks for fixing it though!
